"
# Molecule

Molecule is a component oriented framework for Pharo. His Component architecture approach provide an adapted structuration to graphic user interface (GUI) or another software application wich need Component features.

Molecule provide a way to describe a software application as a components group. Components communicate by use of services, parameters and events propagation. It is a Pharo implementation of the Lightweight Corba Component Model (Lightweight CCM).

## Getting Started
### Prerequisites

Molecule has no dependencies.

## Examples

Examples are in the package 'Molecule-Examples'.

##Credits

    Pierre Laborde - Initial work - labordep
    Eric Le Pors - Initial work - ELePors
    Nolwenn Fournier - Initial work - nolwennfournier
    Alain Plantec - Initial work - plantec

##License

This project is licensed under the MIT License - see the LICENSE file for details.
"
Class {
	#name : #ManifestMolecule,
	#superclass : #PackageManifest,
	#category : #'Molecule-Manifest'
}
