"
I am added and removed by test: MolComponentFactoryTest>>#testCreateComponentClassWithType
"
Class {
	#name : #MolCompleteComponentTestImpl,
	#superclass : #MolAbstractComponentImpl,
	#traits : 'MolCompleteComponent + MolUsedParameters + MolUsedServices + MolUsedEvents',
	#classTraits : 'MolCompleteComponent classTrait + MolUsedParameters classTrait + MolUsedServices classTrait + MolUsedEvents classTrait',
	#category : #'Molecule-Tests-Resources - Generated'
}
