"
I am added and removed by test: MolComponentFactoryTest>>#testMakeAComponentFromScratch
"
Trait {
	#name : #MolTestGeneratedComponentParameters,
	#traits : 'MolComponentParameters',
	#classTraits : 'MolComponentParameters classTrait',
	#category : #'Molecule-Tests-Resources - Generated'
}

{ #category : #parameters }
MolTestGeneratedComponentParameters >> testGeneratedParameterA [
]

{ #category : #parameters }
MolTestGeneratedComponentParameters >> testGeneratedParameterB [
]
