"
I am added and removed by test: MolComponentFactoryTest>>#testMakeAComponentFromScratchAlternative4
"
Trait {
	#name : #MolTestGeneratedComponentServices,
	#traits : 'MolComponentServices',
	#classTraits : 'MolComponentServices classTrait',
	#category : #'Molecule-Tests-Resources - Generated'
}

{ #category : #services }
MolTestGeneratedComponentServices >> testGeneratedServiceA [
]

{ #category : #services }
MolTestGeneratedComponentServices >> testGeneratedServiceB [
]
