"
I am added and removed by test: MolComponentFactoryTest>>#testMakeAComponentFromScratch
"
Trait {
	#name : #MolTestGeneratedComponentEvents,
	#traits : 'MolComponentEvents',
	#classTraits : 'MolComponentEvents classTrait',
	#category : #'Molecule-Tests-Resources - Generated'
}

{ #category : #events }
MolTestGeneratedComponentEvents >> testGeneratedEventA [
]

{ #category : #events }
MolTestGeneratedComponentEvents >> testGeneratedEventB [
]
