Class {
	#name : #MolTestGeneratedComponentImpl,
	#superclass : #MolAbstractComponentImpl,
	#traits : 'MolTestGeneratedComponentType + MolTestGeneratedComponentParameters + MolTestGeneratedComponentServices + MolTestGeneratedComponentEvents',
	#classTraits : 'MolTestGeneratedComponentType classTrait + MolTestGeneratedComponentParameters classTrait + MolTestGeneratedComponentServices classTrait + MolTestGeneratedComponentEvents classTrait',
	#category : #'Molecule-Tests-Resources - Generated'
}
