"
I represent an implementation of a BasicComponent.
I am a component implementation because I have trait ComponentImpl.
"
Class {
	#name : 'MolBasicTraitComponentImpl',
	#superclass : 'Object',
	#traits : 'MolComponentImpl + MolBasicComponent',
	#classTraits : 'MolComponentImpl classTrait + MolBasicComponent classTrait',
	#category : 'Molecule-Tests-Resources - Components',
	#package : 'Molecule-Tests',
	#tag : 'Resources - Components'
}
